### ISSUE TITLE
Loader doesn't appear

### ISSUE THREAD

**Issue by alok-srivastav** [biig-io/ngx-smart-loader#5]

**Comment by Et3rnal** [comment]
Make sure you add "node_modules/ngx-smart-loader/ngx-smart-loader.scss" to your style[] in angular.json
This is what I had to do! it's not mentioned in the documentation

**Comment by maximelafarie** [comment]
Thank you @Et3rnal! 👍 

I'll add it in the readme on the next release.

**Comment by alok-srivastav** [comment]
Thank you @Et3rnal 
I found it way earlier!!

By the way, thanks

**Comment by marco10024** [comment]
will be done in next release
