### ISSUE TITLE
Couldn't implement multiple loaders

### ISSUE THREAD

**Issue by varpitoo** [biig-io/ngx-smart-loader#8]
Couldn't implement multiple loaders in multiple components on a single page through web services. Getting error as:  **Cannot find the loader of undefined.**

Please help!!

Thanks

**Comment by maximelafarie** [comment]
Hi @varpitoo, can you provide any code example, use case or live example like [stackblitz](https://stackblitz.com/fork/angular) please?

**Comment by varpitoo** [comment]
Hey @maximelafarie , thanks for replying.

I want to implement multiple loaders on various components of a page  which I implemented using different identifiers.
Is there any way that we can accomplish it using one identifier or any other better way..!?

Thanks

**Comment by maximelafarie** [comment]
Hi @varpitoo, after this long time, it has been officially fixed in #12, and a new 2.0 release will be published really soon! 👌 

Cheers! 🖖
