### ISSUE TITLE
Stop any loader

### ISSUE THREAD

**Issue by Et3rnal** [biig-io/ngx-smart-loader#9]
It would be nice to have a way to stop any/all loader without a specific identifier.
This can be used inside something like catchError()

**Comment by maximelafarie** [comment]
Hi @Et3rnal and thank you for submitting your feature request.

It's an interesting feature and we will develop it soon! To sum up, it will be a method to stop any **running** loader (tell me if I'm wrong with what you thought).

Stay tuned of the release progress of this feature on this issue. 😉

Cheers! 🖖

**Comment by Et3rnal** [comment]
Yes you are right "a method to stop any running loader"
Thank you :)

**Comment by maximelafarie** [comment]
Hi @Et3rnal! After this long time, it has been fixed in #12! New 2.0 release soon!
Cheers! 🖖
